### ISSUE TITLE
Issue at specific resolutions

### ISSUE THREAD

**Issue by ACMENEWS** [skeletonframework/skeletonframework#20]
I enjoy this framework.  It needs a fix which is easier to explain by attaching the image which is attached to this issue. 

<img width="650" alt="screen shot 2015-12-17 at 8 48 58 pm" src="https://cloud.githubusercontent.com/assets/16344908/11888171/7aeddddc-a500-11e5-9bd2-fc9d01534ab1.png">

**Comment by benhinchley** [comment]
@skeletonframework/core looks like we need look at the breakpoints for this example
