### ISSUE TITLE
Skeleton Build System

### ISSUE THREAD

**Issue by gld1982ltd** [skeletonframework/skeletonframework#26]
In 2.0 we are dropping gulp. We are striving for minimal dependencies. 
Everything works as of now, so you can go ahead and try out 2.0. 

The build system itself only requires postcss and some postcss plugins for a dependency count of 7.

For the server, we are using browsersync (I think I forgot to --save-dev browser-sync..), but in the future we will be writing up a custom server with node's http and using websockets(?) to reload the page.

For our watcher, we are using npm-scripts-watcher, but again, in the future we will be writing up a custom watcher built with node's fs.watch.

The end goal is to rely mostly on postcss, it's plugins, and a few others as dependencies. Everything else can be handled directly by node's api with a little socket.io magic?

Suggestions and comments please.

**Comment by enlore** [comment]
I'd say writing custom modules for those purposes (serve, watch) is a waste of effort pursuant to the goals of Skeleton Framework.  If you want to do all that, then hey go for it (sounds like fun, actually), but do so as projects separate from Skeleton Framework and then include them as dependencies.

As it stands, the goals for Skeleton Framework, as they've evolved to date, are to reinvigorate Skeleton's usage by freshening up the core CSS, creating a useful listing of quality UI components (that have been lightly adapted to work well with Skeleton if need be), and connecting the Skeleton Framework presence to the existing Skeleton community.

Keeping our dep count low doesn't serve those goals.  Keeping the build process simple may serve those goals, but the only reason we need a build process at all is for building out the core CSS. We do that for the sake of the standard dev and build process, or for custom builds.  People that want to download and use default Skeleton (via our dist builds) can just do so. For the custom stuff, we'll have decent docs.

**Comment by gld1982ltd** [comment]
It's true keeping the dep low count is not a primary goal for Skeleton Framework, but I still don't see a need for 300 deps just to build one css file. NO, there are not 300 dependencies in our package.json, but there are 301 deps pulled in with our current npm install. 

I saw an opportunity to make Skeleton Framework light on the development end as well. With node 5.5 api we can do more with less. Since it seems to be my personal agenda, I will take it on myself. I AM having fun with it! As far as making the modules separate, wouldn't it take more effort to make sure the modules work with anything, than it would be to make the modules work just for skeleton?

BTW...You are doing a great job on the css @enlore .Keep up the good work.
